# Pipeline CI/CD do microsserviço "flag".
# Toda a lógica está em _reusable-cicd.yml.

name: CI - flag-service

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'services/flag-service/**'
      - 'gitops/base/flag/**'
      - '.github/workflows/ci-flag.yml'
      - '.github/workflows/_reusable-cicd.yml'
  push:
    branches: [ main ]
    paths:
      - 'services/flag-service/**'
      - 'gitops/base/flag/**'
      - '.github/workflows/ci-flag.yml'
      - '.github/workflows/_reusable-cicd.yml'

jobs:
  cicd:
    uses: ./.github/workflows/_reusable-cicd.yml
    with:
      service: flag
      language: python
      ecr_repository: togglemaster-flag
      gitops_path: gitops/base/flag/deployment.yaml
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:     ${{ secrets.AWS_SESSION_TOKEN }}
      GITOPS_TOKEN:          ${{ secrets.GITOPS_TOKEN }}
