
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: self-healing-webhook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Apontar para o MESMO repo GitOps, path = base/self-healing
    repoURL: https://github.com/vitorgramacho/togglemaster-tc4.git
    targetRevision: main
    path: gitops/base/self-healing
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
