
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Substituir pelo repo real no momento do bootstrap (ver DEPLOYMENT.md)
    repoURL: https://github.com/vitorgramacho/togglemaster-ftc3.git
    targetRevision: main
    path: gitops/base/observability
    # Ordena pelo prefixo numérico nos arquivos: 00- < 01- < ... < 08-
    directory:
      recurse: false
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
