services:
  # Banco para auth
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"] 
      interval: 5s 
      timeout: 5s 
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
      - ./auth-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - togglemaster

  postgres-targeting:
    image: postgres:15
    container_name: postgres-targeting
    environment:
      POSTGRES_USER: ${TARGETING_DB_USER}
      POSTGRES_PASSWORD: ${TARGETING_DB_PASSWORD}
      POSTGRES_DB: ${TARGETING_DB_NAME}
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${TARGETING_DB_USER} -d ${TARGETING_DB_NAME}"] 
      interval: 5s 
      timeout: 5s 
      retries: 5
    ports:
      - "5434:5432"
    volumes:
      - postgres_targeting_data:/var/lib/postgresql/data
      - ./targeting-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - togglemaster

  # Banco para flag-service
  postgres-flag:
    image: postgres:15
    container_name: postgres-flag
    environment:
      POSTGRES_USER: ${FLAG_DB_USER}
      POSTGRES_PASSWORD: ${FLAG_DB_PASSWORD}
      POSTGRES_DB: ${FLAG_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${FLAG_DB_USER} -d ${FLAG_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres_flag_data:/var/lib/postgresql/data
      - ./flag-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - togglemaster

  # Redis para evaluation-service
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck: 
      test: ["CMD", "redis-cli", "ping"] 
      interval: 10s 
      timeout: 5s 
      retries: 3
    networks:
      - togglemaster

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - EDGE_PORT=4566
      - AWS_SQS_URL=${AWS_SQS_URL}
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - togglemaster

  aws-cli-init:
    image: amazon/aws-cli:latest
    container_name: aws-cli-init
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - ./localstack/init-aws.sh:/init-aws.sh
    entrypoint: ["/bin/sh", "/init-aws.sh"]
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    restart: "no"
    networks:
      - togglemaster


  # Auth-service
  auth-service:
    build: ./auth-service
    env_file: 
      - .env  
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: ${AUTH_DATABASE_URL}
      MASTER_KEY: ${AUTH_MASTER_KEY}
    depends_on:
      postgres-auth:
          condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8001/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - togglemaster

  # Flag-service
  flag-service:
    build: ./flag-service
    container_name: flag-service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: ${FLAG_DATABASE_URL}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    depends_on:
      postgres-flag:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - togglemaster

  # Targeting-service
  targeting-service:
    build: ./targeting-service
    container_name: targeting-service
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: ${TARGETING_DATABASE_URL}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    depends_on:
      postgres-targeting:
          condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8003/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - togglemaster

  # Evaluation-service
  evaluation-service:
    build: ./evaluation-service
    container_name: evaluation-service
    ports:
      - "8004:8004"
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_SQS_URL: ${AWS_SQS_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      LOCALSTACK_ENDPOINT: ${LOCALSTACK_ENDPOINT}
      REDIS_URL: ${REDIS_URL}
      FLAG_SERVICE_URL: ${FLAG_SERVICE_URL}
      TARGETING_SERVICE_URL: ${TARGETING_SERVICE_URL}
      SERVICE_API_KEY: ${SERVICE_API_KEY}
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8004/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - togglemaster

  # Analytics-service
  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    ports:
      - "8005:8005"
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_SQS_URL: ${AWS_SQS_URL}
      AWS_DYNAMODB_TABLE: ${AWS_DYNAMODB_TABLE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      LOCALSTACK_ENDPOINT: ${LOCALSTACK_ENDPOINT}
    depends_on:
      localstack:
        condition: service_healthy
      aws-cli-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8005/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - togglemaster

volumes:
  postgres_auth_data:
  postgres_flag_data:
  postgres_targeting_data:
  localstack_data:

networks:
  togglemaster:
    driver: bridge
