apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: analytics-namespace
  labels: { app: analytics-service }
spec:
  replicas: 2
  selector: { matchLabels: { app: analytics-service } }
  template:
    metadata: { labels: { app: analytics-service } }
    spec:
      containers:
        - name: analytics-service
          image: 604720765096.dkr.ecr.us-east-1.amazonaws.com/togglemaster-analytics:v1.0.0-3db532b
          imagePullPolicy: Always
          ports: [ { containerPort: 8005 } ]
          env:
            - { name: PORT, value: "8005" }
            - name: REDIS_URL
              valueFrom: { configMapKeyRef: { name: togglemaster-config, key: REDIS_URL } }
            - name: AWS_REGION
              valueFrom: { configMapKeyRef: { name: togglemaster-config, key: AWS_REGION } }
            - name: AWS_SQS_URL
              valueFrom: { configMapKeyRef: { name: togglemaster-config, key: AWS_SQS_URL } }
            - name: AWS_DYNAMODB_TABLE
              valueFrom: { configMapKeyRef: { name: togglemaster-config, key: AWS_DYNAMODB_TABLE } }
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
          readinessProbe: { httpGet: { path: /health, port: 8005 }, initialDelaySeconds: 10, periodSeconds: 5 }
          livenessProbe:  { httpGet: { path: /health, port: 8005 }, initialDelaySeconds: 30, periodSeconds: 15 }
