apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: targeting-namespace
  labels: { app: targeting-service }
spec:
  replicas: 2
  selector: { matchLabels: { app: targeting-service } }
  template:
    metadata: { labels: { app: targeting-service } }
    spec:
      containers:
        - name: targeting-service
          image: 604720765096.dkr.ecr.us-east-1.amazonaws.com/togglemaster-targeting:v1.0.0-7d341bf
          imagePullPolicy: Always
          ports: [ { containerPort: 8003 } ]
          env:
            - { name: PORT, value: "8003" }
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef: { name: togglemaster-db-secret, key: DATABASE_URL }
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef: { name: togglemaster-config, key: AUTH_SERVICE_URL }
            - name: FLAG_SERVICE_URL
              valueFrom:
                configMapKeyRef: { name: togglemaster-config, key: FLAG_SERVICE_URL }
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "300m", memory: "256Mi" }
          readinessProbe: { httpGet: { path: /health, port: 8003 }, initialDelaySeconds: 10, periodSeconds: 5 }
          livenessProbe:  { httpGet: { path: /health, port: 8003 }, initialDelaySeconds: 30, periodSeconds: 15 }
